title: QLA-ML-DS Unit Research Activities
description: ""


navigation:
  Home: "/"
  Weekly seminars: "/weekly_seminars"
  Study Groups: "/study_groups"
  Tutorials: "/tutorials"
  Events: "/events"
  People: "/people"
  
  


markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
