title: QLA-ML-DS Unit Research Activities
description: ""


navigation:
  Home: "/"
  Lectures: "/speakers"
  Organizers: "/organizers"
  T2P Workshop: "/t2pworkshop"
  

2021:
  Home: "/2021/"
  Gather.Town: "https://eventhosts.gather.town/app/521DLws31zFHszdo/GTRL%20@%20ICLR%202021"
  Call for Papers: "/2021/cfp"
  Challenge: "/2021/challenge"
  Speakers: "/2021/speakers"
  Organizers: "/2021/organizers"
  Accepted Papers: "/2021/papers"
  Schedule: "https://iclr.cc/virtual/2021/workshop/2137"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
